#############################################################################
# Makefile for building: Kalk
# Generated by qmake (3.1) (Qt 5.9.1)
# Project:  Kalk.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt5/bin/qmake -o Makefile Kalk.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I. -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -isystem /usr/include/libdrm -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64
QMAKE         = /usr/lib/x86_64-linux-gnu/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/x86_64-linux-gnu/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/x86_64-linux-gnu/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = Kalk1.0.0
DISTDIR = /home/giovanni/Scrivania/Kalk/.tmp/Kalk1.0.0
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS) -L/usr/X11R6/lib64 -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		CONTROLLER/controlbuttons.cpp \
		MODEL/angolo.cpp \
		MODEL/colore.cpp \
		MODEL/container.cpp \
		MODEL/pentagono.cpp \
		MODEL/poligono.cpp \
		MODEL/punto.cpp \
		MODEL/quadrato.cpp \
		MODEL/quadrilatero.cpp \
		MODEL/rettangolo.cpp \
		MODEL/rgb.cpp \
		MODEL/triangolo.cpp \
		VIEW/boxbutton.cpp \
		VIEW/colorcreator.cpp \
		VIEW/dataarea.cpp \
		VIEW/drawarea.cpp \
		VIEW/exception.cpp \
		VIEW/operandselector.cpp \
		VIEW/pentagoncreator.cpp \
		VIEW/polygoncreator.cpp \
		VIEW/quadrilateralcreator.cpp \
		VIEW/trianglecreator.cpp \
		VIEW/window.cpp moc_boxbutton.cpp \
		moc_colorcreator.cpp \
		moc_dataarea.cpp \
		moc_drawarea.cpp \
		moc_drawwindow.cpp \
		moc_operandselector.cpp \
		moc_pentagoncreator.cpp \
		moc_polygoncreator.cpp \
		moc_quadrilateralcreator.cpp \
		moc_trianglecreator.cpp \
		moc_window.cpp
OBJECTS       = main.o \
		controlbuttons.o \
		angolo.o \
		colore.o \
		container.o \
		pentagono.o \
		poligono.o \
		punto.o \
		quadrato.o \
		quadrilatero.o \
		rettangolo.o \
		rgb.o \
		triangolo.o \
		boxbutton.o \
		colorcreator.o \
		dataarea.o \
		drawarea.o \
		exception.o \
		operandselector.o \
		pentagoncreator.o \
		polygoncreator.o \
		quadrilateralcreator.o \
		trianglecreator.o \
		window.o \
		moc_boxbutton.o \
		moc_colorcreator.o \
		moc_dataarea.o \
		moc_drawarea.o \
		moc_drawwindow.o \
		moc_operandselector.o \
		moc_pentagoncreator.o \
		moc_polygoncreator.o \
		moc_quadrilateralcreator.o \
		moc_trianglecreator.o \
		moc_window.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		Kalk.pro CONTROLLER/controlbuttons.h \
		MODEL/angolo.h \
		MODEL/colore.h \
		MODEL/container.h \
		MODEL/pentagono.h \
		MODEL/poligono.h \
		MODEL/punto.h \
		MODEL/quadrato.h \
		MODEL/quadrilatero.h \
		MODEL/rettangolo.h \
		MODEL/rgb.h \
		MODEL/triangolo.h \
		VIEW/boxbutton.h \
		VIEW/colorcreator.h \
		VIEW/dataarea.h \
		VIEW/drawarea.h \
		VIEW/drawwindow.h \
		VIEW/exception.h \
		VIEW/operandselector.h \
		VIEW/pentagoncreator.h \
		VIEW/polygoncreator.h \
		VIEW/quadrilateralcreator.h \
		VIEW/trianglecreator.h \
		VIEW/window.h main.cpp \
		CONTROLLER/controlbuttons.cpp \
		MODEL/angolo.cpp \
		MODEL/colore.cpp \
		MODEL/container.cpp \
		MODEL/pentagono.cpp \
		MODEL/poligono.cpp \
		MODEL/punto.cpp \
		MODEL/quadrato.cpp \
		MODEL/quadrilatero.cpp \
		MODEL/rettangolo.cpp \
		MODEL/rgb.cpp \
		MODEL/triangolo.cpp \
		VIEW/boxbutton.cpp \
		VIEW/colorcreator.cpp \
		VIEW/dataarea.cpp \
		VIEW/drawarea.cpp \
		VIEW/exception.cpp \
		VIEW/operandselector.cpp \
		VIEW/pentagoncreator.cpp \
		VIEW/polygoncreator.cpp \
		VIEW/quadrilateralcreator.cpp \
		VIEW/trianglecreator.cpp \
		VIEW/window.cpp
QMAKE_TARGET  = Kalk
DESTDIR       = 
TARGET        = Kalk


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Kalk.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		Kalk.pro \
		/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Gui.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Core.prl
	$(QMAKE) -o Makefile Kalk.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
Kalk.pro:
/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl:
/usr/lib/x86_64-linux-gnu/libQt5Gui.prl:
/usr/lib/x86_64-linux-gnu/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile Kalk.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents CONTROLLER/controlbuttons.h MODEL/angolo.h MODEL/colore.h MODEL/container.h MODEL/pentagono.h MODEL/poligono.h MODEL/punto.h MODEL/quadrato.h MODEL/quadrilatero.h MODEL/rettangolo.h MODEL/rgb.h MODEL/triangolo.h VIEW/boxbutton.h VIEW/colorcreator.h VIEW/dataarea.h VIEW/drawarea.h VIEW/drawwindow.h VIEW/exception.h VIEW/operandselector.h VIEW/pentagoncreator.h VIEW/polygoncreator.h VIEW/quadrilateralcreator.h VIEW/trianglecreator.h VIEW/window.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp CONTROLLER/controlbuttons.cpp MODEL/angolo.cpp MODEL/colore.cpp MODEL/container.cpp MODEL/pentagono.cpp MODEL/poligono.cpp MODEL/punto.cpp MODEL/quadrato.cpp MODEL/quadrilatero.cpp MODEL/rettangolo.cpp MODEL/rgb.cpp MODEL/triangolo.cpp VIEW/boxbutton.cpp VIEW/colorcreator.cpp VIEW/dataarea.cpp VIEW/drawarea.cpp VIEW/exception.cpp VIEW/operandselector.cpp VIEW/pentagoncreator.cpp VIEW/polygoncreator.cpp VIEW/quadrilateralcreator.cpp VIEW/trianglecreator.cpp VIEW/window.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
	g++ -m64 -pipe -O2 -Wall -W -dM -E -o moc_predefs.h /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_boxbutton.cpp moc_colorcreator.cpp moc_dataarea.cpp moc_drawarea.cpp moc_drawwindow.cpp moc_operandselector.cpp moc_pentagoncreator.cpp moc_polygoncreator.cpp moc_quadrilateralcreator.cpp moc_trianglecreator.cpp moc_window.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_boxbutton.cpp moc_colorcreator.cpp moc_dataarea.cpp moc_drawarea.cpp moc_drawwindow.cpp moc_operandselector.cpp moc_pentagoncreator.cpp moc_polygoncreator.cpp moc_quadrilateralcreator.cpp moc_trianglecreator.cpp moc_window.cpp
moc_boxbutton.cpp: VIEW/operandselector.h \
		MODEL/poligono.h \
		MODEL/punto.h \
		MODEL/angolo.h \
		MODEL/colore.h \
		MODEL/rgb.h \
		MODEL/container.h \
		VIEW/boxbutton.h \
		VIEW/boxbutton.h \
		moc_predefs.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/giovanni/Scrivania/Kalk -I/home/giovanni/Scrivania/Kalk -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include VIEW/boxbutton.h -o moc_boxbutton.cpp

moc_colorcreator.cpp: MODEL/colore.h \
		VIEW/operandselector.h \
		MODEL/poligono.h \
		MODEL/punto.h \
		MODEL/angolo.h \
		MODEL/rgb.h \
		MODEL/container.h \
		VIEW/boxbutton.h \
		VIEW/colorcreator.h \
		moc_predefs.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/giovanni/Scrivania/Kalk -I/home/giovanni/Scrivania/Kalk -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include VIEW/colorcreator.h -o moc_colorcreator.cpp

moc_dataarea.cpp: MODEL/poligono.h \
		MODEL/punto.h \
		MODEL/angolo.h \
		MODEL/colore.h \
		MODEL/rgb.h \
		VIEW/dataarea.h \
		moc_predefs.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/giovanni/Scrivania/Kalk -I/home/giovanni/Scrivania/Kalk -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include VIEW/dataarea.h -o moc_dataarea.cpp

moc_drawarea.cpp: MODEL/poligono.h \
		MODEL/punto.h \
		MODEL/angolo.h \
		MODEL/colore.h \
		MODEL/rgb.h \
		VIEW/drawarea.h \
		moc_predefs.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/giovanni/Scrivania/Kalk -I/home/giovanni/Scrivania/Kalk -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include VIEW/drawarea.h -o moc_drawarea.cpp

moc_drawwindow.cpp: VIEW/drawwindow.h \
		moc_predefs.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/giovanni/Scrivania/Kalk -I/home/giovanni/Scrivania/Kalk -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include VIEW/drawwindow.h -o moc_drawwindow.cpp

moc_operandselector.cpp: MODEL/poligono.h \
		MODEL/punto.h \
		MODEL/angolo.h \
		MODEL/colore.h \
		MODEL/rgb.h \
		MODEL/container.h \
		VIEW/boxbutton.h \
		VIEW/operandselector.h \
		VIEW/operandselector.h \
		moc_predefs.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/giovanni/Scrivania/Kalk -I/home/giovanni/Scrivania/Kalk -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include VIEW/operandselector.h -o moc_operandselector.cpp

moc_pentagoncreator.cpp: MODEL/pentagono.h \
		MODEL/poligono.h \
		MODEL/punto.h \
		MODEL/angolo.h \
		MODEL/colore.h \
		MODEL/rgb.h \
		VIEW/operandselector.h \
		MODEL/container.h \
		VIEW/boxbutton.h \
		VIEW/pentagoncreator.h \
		moc_predefs.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/giovanni/Scrivania/Kalk -I/home/giovanni/Scrivania/Kalk -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include VIEW/pentagoncreator.h -o moc_pentagoncreator.cpp

moc_polygoncreator.cpp: VIEW/trianglecreator.h \
		MODEL/triangolo.h \
		MODEL/poligono.h \
		MODEL/punto.h \
		MODEL/angolo.h \
		MODEL/colore.h \
		MODEL/rgb.h \
		VIEW/operandselector.h \
		MODEL/container.h \
		VIEW/boxbutton.h \
		VIEW/quadrilateralcreator.h \
		MODEL/quadrilatero.h \
		MODEL/quadrato.h \
		VIEW/pentagoncreator.h \
		MODEL/pentagono.h \
		VIEW/polygoncreator.h \
		moc_predefs.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/giovanni/Scrivania/Kalk -I/home/giovanni/Scrivania/Kalk -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include VIEW/polygoncreator.h -o moc_polygoncreator.cpp

moc_quadrilateralcreator.cpp: MODEL/quadrilatero.h \
		MODEL/poligono.h \
		MODEL/punto.h \
		MODEL/angolo.h \
		MODEL/colore.h \
		MODEL/rgb.h \
		MODEL/quadrato.h \
		VIEW/operandselector.h \
		MODEL/container.h \
		VIEW/boxbutton.h \
		VIEW/quadrilateralcreator.h \
		moc_predefs.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/giovanni/Scrivania/Kalk -I/home/giovanni/Scrivania/Kalk -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include VIEW/quadrilateralcreator.h -o moc_quadrilateralcreator.cpp

moc_trianglecreator.cpp: MODEL/triangolo.h \
		MODEL/poligono.h \
		MODEL/punto.h \
		MODEL/angolo.h \
		MODEL/colore.h \
		MODEL/rgb.h \
		VIEW/operandselector.h \
		MODEL/container.h \
		VIEW/boxbutton.h \
		VIEW/trianglecreator.h \
		moc_predefs.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/giovanni/Scrivania/Kalk -I/home/giovanni/Scrivania/Kalk -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include VIEW/trianglecreator.h -o moc_trianglecreator.cpp

moc_window.cpp: VIEW/drawarea.h \
		MODEL/poligono.h \
		MODEL/punto.h \
		MODEL/angolo.h \
		MODEL/colore.h \
		MODEL/rgb.h \
		VIEW/dataarea.h \
		VIEW/polygoncreator.h \
		VIEW/trianglecreator.h \
		MODEL/triangolo.h \
		VIEW/operandselector.h \
		MODEL/container.h \
		VIEW/boxbutton.h \
		VIEW/quadrilateralcreator.h \
		MODEL/quadrilatero.h \
		MODEL/quadrato.h \
		VIEW/pentagoncreator.h \
		MODEL/pentagono.h \
		VIEW/colorcreator.h \
		VIEW/window.h \
		moc_predefs.h \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/giovanni/Scrivania/Kalk -I/home/giovanni/Scrivania/Kalk -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include VIEW/window.h -o moc_window.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

main.o: main.cpp MODEL/rgb.h \
		MODEL/colore.h \
		MODEL/triangolo.h \
		MODEL/poligono.h \
		MODEL/punto.h \
		MODEL/angolo.h \
		MODEL/quadrato.h \
		MODEL/quadrilatero.h \
		MODEL/rettangolo.h \
		MODEL/pentagono.h \
		VIEW/colorcreator.h \
		VIEW/operandselector.h \
		MODEL/container.h \
		VIEW/boxbutton.h \
		VIEW/drawarea.h \
		VIEW/trianglecreator.h \
		VIEW/quadrilateralcreator.h \
		VIEW/pentagoncreator.h \
		VIEW/polygoncreator.h \
		VIEW/dataarea.h \
		VIEW/window.h \
		VIEW/exception.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

controlbuttons.o: CONTROLLER/controlbuttons.cpp CONTROLLER/controlbuttons.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o controlbuttons.o CONTROLLER/controlbuttons.cpp

angolo.o: MODEL/angolo.cpp MODEL/angolo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o angolo.o MODEL/angolo.cpp

colore.o: MODEL/colore.cpp MODEL/colore.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o colore.o MODEL/colore.cpp

container.o: MODEL/container.cpp MODEL/container.h \
		MODEL/poligono.h \
		MODEL/punto.h \
		MODEL/angolo.h \
		MODEL/colore.h \
		MODEL/rgb.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o container.o MODEL/container.cpp

pentagono.o: MODEL/pentagono.cpp MODEL/pentagono.h \
		MODEL/poligono.h \
		MODEL/punto.h \
		MODEL/angolo.h \
		MODEL/colore.h \
		MODEL/rgb.h \
		MODEL/triangolo.h \
		MODEL/quadrilatero.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pentagono.o MODEL/pentagono.cpp

poligono.o: MODEL/poligono.cpp MODEL/punto.h \
		MODEL/angolo.h \
		MODEL/poligono.h \
		MODEL/colore.h \
		MODEL/rgb.h \
		MODEL/pentagono.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o poligono.o MODEL/poligono.cpp

punto.o: MODEL/punto.cpp MODEL/punto.h \
		MODEL/angolo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o punto.o MODEL/punto.cpp

quadrato.o: MODEL/quadrato.cpp MODEL/quadrato.h \
		MODEL/quadrilatero.h \
		MODEL/poligono.h \
		MODEL/punto.h \
		MODEL/angolo.h \
		MODEL/colore.h \
		MODEL/rgb.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o quadrato.o MODEL/quadrato.cpp

quadrilatero.o: MODEL/quadrilatero.cpp MODEL/quadrilatero.h \
		MODEL/poligono.h \
		MODEL/punto.h \
		MODEL/angolo.h \
		MODEL/colore.h \
		MODEL/rgb.h \
		MODEL/triangolo.h \
		MODEL/pentagono.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o quadrilatero.o MODEL/quadrilatero.cpp

rettangolo.o: MODEL/rettangolo.cpp MODEL/rettangolo.h \
		MODEL/quadrilatero.h \
		MODEL/poligono.h \
		MODEL/punto.h \
		MODEL/angolo.h \
		MODEL/colore.h \
		MODEL/rgb.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rettangolo.o MODEL/rettangolo.cpp

rgb.o: MODEL/rgb.cpp MODEL/rgb.h \
		MODEL/colore.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rgb.o MODEL/rgb.cpp

triangolo.o: MODEL/triangolo.cpp MODEL/triangolo.h \
		MODEL/poligono.h \
		MODEL/punto.h \
		MODEL/angolo.h \
		MODEL/colore.h \
		MODEL/rgb.h \
		MODEL/quadrilatero.h \
		MODEL/pentagono.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o triangolo.o MODEL/triangolo.cpp

boxbutton.o: VIEW/boxbutton.cpp VIEW/boxbutton.h \
		VIEW/operandselector.h \
		MODEL/poligono.h \
		MODEL/punto.h \
		MODEL/angolo.h \
		MODEL/colore.h \
		MODEL/rgb.h \
		MODEL/container.h \
		VIEW/exception.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o boxbutton.o VIEW/boxbutton.cpp

colorcreator.o: VIEW/colorcreator.cpp VIEW/colorcreator.h \
		MODEL/colore.h \
		VIEW/operandselector.h \
		MODEL/poligono.h \
		MODEL/punto.h \
		MODEL/angolo.h \
		MODEL/rgb.h \
		MODEL/container.h \
		VIEW/boxbutton.h \
		VIEW/exception.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o colorcreator.o VIEW/colorcreator.cpp

dataarea.o: VIEW/dataarea.cpp VIEW/dataarea.h \
		MODEL/poligono.h \
		MODEL/punto.h \
		MODEL/angolo.h \
		MODEL/colore.h \
		MODEL/rgb.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dataarea.o VIEW/dataarea.cpp

drawarea.o: VIEW/drawarea.cpp VIEW/drawarea.h \
		MODEL/poligono.h \
		MODEL/punto.h \
		MODEL/angolo.h \
		MODEL/colore.h \
		MODEL/rgb.h \
		MODEL/triangolo.h \
		MODEL/rettangolo.h \
		MODEL/quadrilatero.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o drawarea.o VIEW/drawarea.cpp

exception.o: VIEW/exception.cpp VIEW/exception.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o exception.o VIEW/exception.cpp

operandselector.o: VIEW/operandselector.cpp VIEW/operandselector.h \
		MODEL/poligono.h \
		MODEL/punto.h \
		MODEL/angolo.h \
		MODEL/colore.h \
		MODEL/rgb.h \
		MODEL/container.h \
		VIEW/boxbutton.h \
		MODEL/triangolo.h \
		MODEL/quadrilatero.h \
		MODEL/pentagono.h \
		VIEW/exception.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o operandselector.o VIEW/operandselector.cpp

pentagoncreator.o: VIEW/pentagoncreator.cpp VIEW/pentagoncreator.h \
		MODEL/pentagono.h \
		MODEL/poligono.h \
		MODEL/punto.h \
		MODEL/angolo.h \
		MODEL/colore.h \
		MODEL/rgb.h \
		VIEW/operandselector.h \
		MODEL/container.h \
		VIEW/boxbutton.h \
		VIEW/exception.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pentagoncreator.o VIEW/pentagoncreator.cpp

polygoncreator.o: VIEW/polygoncreator.cpp VIEW/polygoncreator.h \
		VIEW/trianglecreator.h \
		MODEL/triangolo.h \
		MODEL/poligono.h \
		MODEL/punto.h \
		MODEL/angolo.h \
		MODEL/colore.h \
		MODEL/rgb.h \
		VIEW/operandselector.h \
		MODEL/container.h \
		VIEW/boxbutton.h \
		VIEW/quadrilateralcreator.h \
		MODEL/quadrilatero.h \
		MODEL/quadrato.h \
		VIEW/pentagoncreator.h \
		MODEL/pentagono.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o polygoncreator.o VIEW/polygoncreator.cpp

quadrilateralcreator.o: VIEW/quadrilateralcreator.cpp VIEW/quadrilateralcreator.h \
		MODEL/quadrilatero.h \
		MODEL/poligono.h \
		MODEL/punto.h \
		MODEL/angolo.h \
		MODEL/colore.h \
		MODEL/rgb.h \
		MODEL/quadrato.h \
		VIEW/operandselector.h \
		MODEL/container.h \
		VIEW/boxbutton.h \
		VIEW/exception.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o quadrilateralcreator.o VIEW/quadrilateralcreator.cpp

trianglecreator.o: VIEW/trianglecreator.cpp VIEW/trianglecreator.h \
		MODEL/triangolo.h \
		MODEL/poligono.h \
		MODEL/punto.h \
		MODEL/angolo.h \
		MODEL/colore.h \
		MODEL/rgb.h \
		VIEW/operandselector.h \
		MODEL/container.h \
		VIEW/boxbutton.h \
		VIEW/exception.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o trianglecreator.o VIEW/trianglecreator.cpp

window.o: VIEW/window.cpp VIEW/window.h \
		VIEW/drawarea.h \
		MODEL/poligono.h \
		MODEL/punto.h \
		MODEL/angolo.h \
		MODEL/colore.h \
		MODEL/rgb.h \
		VIEW/dataarea.h \
		VIEW/polygoncreator.h \
		VIEW/trianglecreator.h \
		MODEL/triangolo.h \
		VIEW/operandselector.h \
		MODEL/container.h \
		VIEW/boxbutton.h \
		VIEW/quadrilateralcreator.h \
		MODEL/quadrilatero.h \
		MODEL/quadrato.h \
		VIEW/pentagoncreator.h \
		MODEL/pentagono.h \
		VIEW/colorcreator.h \
		VIEW/exception.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o window.o VIEW/window.cpp

moc_boxbutton.o: moc_boxbutton.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_boxbutton.o moc_boxbutton.cpp

moc_colorcreator.o: moc_colorcreator.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_colorcreator.o moc_colorcreator.cpp

moc_dataarea.o: moc_dataarea.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dataarea.o moc_dataarea.cpp

moc_drawarea.o: moc_drawarea.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_drawarea.o moc_drawarea.cpp

moc_drawwindow.o: moc_drawwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_drawwindow.o moc_drawwindow.cpp

moc_operandselector.o: moc_operandselector.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_operandselector.o moc_operandselector.cpp

moc_pentagoncreator.o: moc_pentagoncreator.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_pentagoncreator.o moc_pentagoncreator.cpp

moc_polygoncreator.o: moc_polygoncreator.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_polygoncreator.o moc_polygoncreator.cpp

moc_quadrilateralcreator.o: moc_quadrilateralcreator.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_quadrilateralcreator.o moc_quadrilateralcreator.cpp

moc_trianglecreator.o: moc_trianglecreator.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_trianglecreator.o moc_trianglecreator.cpp

moc_window.o: moc_window.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_window.o moc_window.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

